language: ruby
rvm:
- 3.0.0
install:
  - bundle install
services:
  - postgresql
script:
  - RAILS_ENV=test ./bin/rails webpacker:compile
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec